#!/bin/sh
export LD_LIBRARY_PATH=/var/local/eeaplonecommonbuildout/eea.plonebuildout.example/parts/libevent/lib

PIDFILE=/var/local/eeaplonecommonbuildout/eea.plonebuildout.example/var/memcached.pid
    case "$1" in
      start)
       /var/local/eeaplonecommonbuildout/eea.plonebuildout.example/parts/memcached/bin/memcached -d -u zope -P $PIDFILE -m 2000
        ;;
      stop)
        kill `cat $PIDFILE`
        rm -f $PIDFILE
        ;;
      restart|force-reload)
        $0 stop
        sleep 1
        $0 start
        ;;
      status)
        ps -p `cat $PIDFILE` > /dev/null 2>&1 && echo Running || echo "Not Running"
        ;;
      *)
        echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
        exit 1
        ;;
    esac
